# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='player_position',
            field=models.CharField(choices=[('RD', 'Right Defense'), ('LD', 'Left Defense'), ('C', 'Center'), ('RW', 'Right Wing'), ('LW', 'Left Wing'), ('G', 'Goaltender')], default='G', max_length=20),
        ),
        migrations.AddField(
            model_name='stat',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
