# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160223_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='image_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
